const actions = {
  SET_STATE: 'web3/SET_STATE',
  CONNECT_WALLET: 'web3/CONNECT_WALLET',
  DISCONNECT_WALLET: 'web3/DISCONNECT_WALLET',
  WALLET_CONNECTED: 'web3/WALLET_CONNECTED',
  WALLET_DISCONNECTED: 'web3/WALLET_DISCONNECTED',
  SET_ENV: 'web3/SET_ENV',
  CLIENT_CONNECTED: 'web3/CLIENT_CONNECTED',
}

export default actions
