const actions = {
    SET_STATE: "hubble/borrow/SET_STATE",
    GET_BORROWING_MARKET_STATE: "hubble/borrow/GET_BORROWING_MARKET_STATE",
    GET_USER_VAULTS: "hubble/borrow/GET_USER_VAULTS",
    CREATE_LOAN_DEPOSIT_BORROW: "hubble/borrow/CREATE_LOAN_DEPOSIT_BORROW",
    GET_STABILITY_POOL_STATE: "hubble/borrow/GET_STABILITY_POOL_STATE",
    GET_STABILITY_PROVIDER_STATE: "hubble/borrow/GET_STABILITY_PROVIDER_STATE",
    AIRDROP_USDH: "hubble/borrow/AIRDROP_USDH",
    AIRDROP_HBB: "hubble/borrow/AIRDROP_HBB",
    APPROVE_STABILITY: "hubble/borrow/APPROVE_STABILITY",
    PROVIDE_STABILITY: "hubble/borrow/PROVIDE_STABILITY",
    WITHDRAW_STABILITY: "hubble/borrow/WITHDRAW_STABILITY",
    HARVEST_LIQUIDATION_GAINS: "hubble/borrow/HARVEST_LIQUIDATION_GAINS",
    TRY_LIQUIDATE: "hubble/borrow/TRY_LIQUIDATE",
    WITHDRAW_COLLATERAL: "hubble/borrow/WITHDRAW_COLLATERAL",
    DEPOSIT_COLLATERAL: "hubble/borrow/DEPOSIT_COLLATERAL",
    BORROW_STABLECOIN: "hubble/borrow/BORROW_STABLECOIN",
    REPAY_LOAN: "hubble/borrow/REPAY_LOAN",
    COFIRM_DIALOG: 'hubble/borrow/CONFIRM',
};

export default actions;
